name: Docker

on:
  push:
    branches:
      - master
      - feature/*
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.goarch }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.goarch }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for postfix-exporter
        id: postfix-exporter-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/postfix-exporter
            banzaicloud/postfix-exporter
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build postfix-exporter
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.postfix-exporter-meta.outputs.tags }}
          labels: ${{ steps.postfix-exporter-meta.outputs.labels }}
